import type { Metadata } from "next";
import NavBar from "@/components/navbar";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"bg-gray-100 text-gray-900 font-sans"}
      >
        <NavBar />
        <div className="p-4">
          {children}
        </div>
      </body>
    </html >
  );
}
