import type { Metadata } from "next";
import { Navbar } from "@/components/navbar";
import "./globals.css";
import SessionProvider from "@/util/SessionProvider";


import { getServerAuthSession } from "@/server/auth";
import { TRPCReactProvider } from "@/trpc/react";
import Loading from "@/components/loading";
import { Suspense } from "react";

// import { HamburgerClicked } from "@/util/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerAuthSession();
  return (
    <html lang="en">
      <body
        className={"text-gray-900 font-sans relative"}
      >
        <TRPCReactProvider>
          <SessionProvider session={session}>
            <Suspense fallback={<Loading />}>
              <Navbar />
              {children}
            </Suspense>
          </SessionProvider>
        </TRPCReactProvider>
      </body>
    </html >
  );
}
